# Generated by Django 6.0.3 on 2026-05-06 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wallet',
            options={'verbose_name': 'Wallet', 'verbose_name_plural': 'Wallets'},
        ),
        migrations.AddField(
            model_name='wallet',
            name='currency',
            field=models.CharField(default='USD', max_length=10),
        ),
    ]
